# Generated by Django 2.2.1 on 2019-05-23 17:05

import ads.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('E', 'Expired'), ('R', 'Rejected'), ('A', 'Active')], default=ads.enums.AdStatusEnum('Pending'), max_length=10),
        ),
    ]
