# Generated by Django 2.2.1 on 2019-05-23 20:41

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190523_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_owner',
            field=models.ForeignKey(default=accounts.models.Seller, on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller'),
        ),
    ]
