# Generated by Django 2.2.1 on 2019-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20190523_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
