# Generated by Django 2.2.1 on 2019-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='ad_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
