# Generated by Django 2.2.1 on 2019-05-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('AUDI', 'AUDI'), ('BMW', 'BMW'), ('MB', 'MERCEDES-BENZ'), ('VW', 'VOLKSWAGEN')], max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('fuel', models.CharField(choices=[('D', 'Diesel'), ('P', 'Petrol'), ('G', 'LPG')], max_length=10)),
                ('color', models.CharField(choices=[('B', 'Black'), ('G', 'Green'), ('Y', 'Yellow'), ('W', 'White')], max_length=10)),
                ('car_type', models.CharField(choices=[('E', 'Estate'), ('H', 'Hatchback'), ('S', 'Saloon')], max_length=10)),
                ('picture', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
            ],
        ),
    ]
